services:
  openlist:
    image: openlist-windows:latest
    build:
      context: .
    restart: always
    volumes:
      - ./data:C:/app/data
      - ./cache:C:/cache
      - ./storage:C:/storage
    ports:
      - '5244:5244'
      - '5245:5245'
    container_name: openlist
   